version: '3'
services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - server

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_NAME=job_tracker
      - DB_PASSWORD=your_secure_password
      - DB_PORT=5432
      - JWT_SECRET=bigfrog5
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=job_tracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_secure_password
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin_password
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
