apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: your-backend-image:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: DB_HOST
              value: "postgres"  # This should match the service name of PostgreSQL in Kubernetes
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "sean"
            - name: DB_PASSWORD
              value: "thomas09"
            - name: DB_NAME
              value: "job_application_db"
